### ISSUE TITLE
Memory Leak in release version

### ISSUE THREAD

**Issue by david-d-h** [RobloxStudio-DiscordRPC/RPC-Client#1]
Creator is aware of problem

**Comment by MatusGuy** [comment]
hi bro, could you give some examples on when it happens? thx

**Comment by MatusGuy** [comment]
Also don't say "in release version" because
1. it implies something else
2. it's embarrassing 😖

**Comment by MatusGuy** [comment]
It has been confirmed that this memory leak only occurs in Windows 11 after closing Roblox Studio while the client is open. I may push a release that might fix this very soon.

**Comment by MatusGuy** [comment]
fixed in version 1.0.0.3 and tweaked in version 1.0.0.4
